import numpy as np
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 15})

names = ['Time','U','I1','I2','D','Ve','IFNe']
t = 480
replicate = 20
parameter = 'k11'
p = [0.0 , 0.25, 0.5, 0.75, 1.0]
VeAUC = np.zeros(len(p))
VeAUCMin = np.zeros(len(p))
VeAUCMax = np.zeros(len(p))
VeMax = np.zeros(len(p))
VeMaxMin = np.zeros(len(p))
VeMaxMax = np.zeros(len(p))
IFNeAUC = np.zeros(len(p))
IFNeAUCMin = np.zeros(len(p))
IFNeAUCMax = np.zeros(len(p))
IFNeMax = np.zeros(len(p))
IFNeMaxMin = np.zeros(len(p))
IFNeMaxMax = np.zeros(len(p))
for i in range(len(p)):
    TVe = np.zeros((replicate))
    TVeMax = np.zeros((replicate))
    TIFNe = np.zeros((replicate))
    TIFNeMax = np.zeros((replicate))
    for r in range(1,replicate+1):
        f = np.genfromtxt('FullModelCellular_%s_%.2f_%i.txt' % (parameter,p[i],r), skip_header=1, delimiter=',', names=names,max_rows=t)
        TVe[r-1] = np.sum(f['Ve'])
        TVeMax[r - 1] = np.amax(f['Ve'])
        TIFNe[r - 1] = np.sum(f['IFNe'])
        TIFNeMax[r - 1] = np.amax(f['IFNe'])
    VeAUC[i] = np.mean(TVe)
    VeAUCMin[i] = np.amin(TVe)
    VeAUCMax[i] = np.amax(TVe)
    VeMax[i] = np.mean(TVeMax)
    VeMaxMin[i] = np.amin(TVeMax)
    VeMaxMax[i] = np.amax(TVeMax)
    IFNeAUC[i] = np.mean(TIFNe)
    IFNeAUCMin[i] = np.amin(TIFNe)
    IFNeAUCMax[i] = np.amax(TIFNe)
    IFNeMax[i] = np.mean(TIFNeMax)
    IFNeMaxMin[i] = np.amin(TIFNeMax)
    IFNeMaxMax[i] = np.amax(TIFNeMax)

plt.plot(p,VeMax,color='#666699',linewidth = 4.0, label = 'Max Virus')
plt.fill_between(p, VeMaxMin,VeMaxMax, facecolor='#666699', interpolate=True, alpha=0.2)
plt.title('Max Virus')
plt.ylabel(r'Virus (PFU/ml)')
plt.xlabel('Parameter Multiplier')
plt.grid()
plt.gca().set_aspect(1.0 / plt.gca().get_data_ratio() * 1.0)
plt.gca().set_xticks(p)
plt.legend(loc=2)
plt.savefig('Fig.Virus_Max_%s.pdf' % parameter,transparent=True)
plt.clf()

plt.plot(p,VeAUC,color='#666699',linewidth = 4.0, label = 'Virus AUC')
plt.fill_between(p, VeAUCMin,VeAUCMax, facecolor='#666699', interpolate=True, alpha=0.2)
plt.title('Virus AUC')
plt.ylabel(r'Virus AUC (PFU/ml)')
plt.xlabel('Parameter Multiplier')
plt.grid()
plt.gca().set_aspect(1.0 / plt.gca().get_data_ratio() * 1.0)
plt.gca().set_xticks(p)
plt.legend(loc=2)
plt.savefig('Fig.Virus_AUC_%s.pdf' % parameter,transparent=True)
plt.clf()

plt.plot(p,IFNeAUC,color='#993300',linewidth = 4.0, label = 'IFN AUC')
plt.fill_between(p, IFNeAUCMin,IFNeAUCMax, facecolor='#993300', interpolate=True, alpha=0.2)
plt.title('IFN AUC')
plt.ylabel(r'IFN AUC ($\mu$M)')
plt.xlabel('Parameter Multiplier')
plt.grid()
plt.gca().set_aspect(1.0 / plt.gca().get_data_ratio() * 1.0)
plt.gca().set_xticks(p)
plt.legend(loc=2)
plt.savefig('Fig.IFNe_AUC_%s.pdf' % parameter,transparent=True)
plt.clf()

plt.plot(p,IFNeMax,color='#993300',linewidth = 4.0, label = 'Max IFN')
plt.fill_between(p, IFNeMaxMin,IFNeMaxMax, facecolor='#993300', interpolate=True, alpha=0.2)
plt.title('Max IFN')
plt.ylabel(r'IFN ($\mu$M)')
plt.xlabel('Parameter Multiplier')
plt.grid()
plt.gca().set_aspect(1.0 / plt.gca().get_data_ratio() * 1.0)
plt.gca().set_xticks(p)
plt.legend(loc=2)
plt.savefig('Fig.IFNe_Max_%s.pdf' % parameter,transparent=True)